# Generated by Django 2.2.4 on 2020-01-17 02:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='districs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('Notes1', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='states',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('Notes', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User_detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('mobile', models.CharField(max_length=10, null=True)),
                ('aadhar', models.CharField(max_length=12, null=True)),
                ('gender', models.CharField(max_length=12, null=True)),
                ('language', models.CharField(max_length=12, null=True)),
                ('size', models.CharField(max_length=12, null=True)),
                ('id_proof', models.CharField(max_length=100, null=True)),
                ('photo', models.FileField(null=True, upload_to='')),
                ('dis', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='SIH.districs')),
                ('states1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='SIH.states')),
                ('usr', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
