# Generated by Django 2.2.4 on 2020-01-17 02:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SIH', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='districs',
            name='Notes1',
        ),
        migrations.RemoveField(
            model_name='states',
            name='Notes',
        ),
        migrations.CreateModel(
            name='states_notes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('states1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='SIH.states')),
            ],
        ),
        migrations.CreateModel(
            name='districs_notes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('dis', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='SIH.districs')),
            ],
        ),
    ]
