# Generated by Django 2.2.4 on 2020-01-30 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SIH', '0003_mymodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='pest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pest_name', models.CharField(max_length=100, null=True)),
                ('photo', models.FileField(null=True, upload_to='')),
            ],
        ),
    ]
