# Generated by Django 2.2.4 on 2020-01-31 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SIH', '0004_pest'),
    ]

    operations = [
        migrations.AddField(
            model_name='pest',
            name='long_disc',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='pest',
            name='short_disc',
            field=models.TextField(null=True),
        ),
        migrations.CreateModel(
            name='Pestsolution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('demage', models.TextField(blank=True, null=True)),
                ('Preventing', models.TextField(blank=True, null=True)),
                ('Tips', models.TextField(blank=True, null=True)),
                ('photo1', models.FileField(blank=True, null=True, upload_to='')),
                ('madecine', models.TextField(blank=True, null=True)),
                ('pest_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='SIH.pest')),
            ],
        ),
    ]
