# Generated by Django 2.2.4 on 2020-01-31 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SIH', '0005_auto_20200131_0501'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_name', models.CharField(max_length=100, null=True)),
                ('photo', models.FileField(null=True, upload_to='')),
                ('short_disc', models.TextField(null=True)),
                ('long_disc', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cropsolution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.FileField(blank=True, null=True, upload_to='')),
                ('photo_dec', models.TextField(blank=True, null=True)),
                ('crop_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='SIH.Crop')),
            ],
        ),
    ]
