# Generated by Django 2.2.4 on 2020-02-01 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SIH', '0006_crop_cropsolution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_detail',
            name='aadhar',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
