# Generated by Django 2.2.4 on 2020-02-01 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SIH', '0007_auto_20200131_2118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_detail',
            name='aadhar',
        ),
    ]
