# Generated by Django 2.2.4 on 2020-02-01 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SIH', '0008_remove_user_detail_aadhar'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_detail',
            name='aadhar',
            field=models.CharField(max_length=12, null=True),
        ),
    ]
