# Generated by Django 2.2.4 on 2020-02-01 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SIH', '0010_auto_20200201_0352'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pest',
            name='demage',
        ),
        migrations.AddField(
            model_name='pestsolution',
            name='demage',
            field=models.TextField(blank=True, null=True),
        ),
    ]
