# Generated by Django 2.2.4 on 2020-02-01 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SIH', '0013_auto_20200201_0408'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pest',
            name='madecine',
        ),
        migrations.RemoveField(
            model_name='pest',
            name='photo1',
        ),
        migrations.AddField(
            model_name='pestsolution',
            name='madecine',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pestsolution',
            name='photo1',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
