# Generated by Django 2.2.4 on 2020-02-01 13:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('SIH', '0014_auto_20200201_0419'),
    ]

    operations = [
        migrations.CreateModel(
            name='soil_detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ph', models.CharField(max_length=10, null=True)),
                ('cn', models.CharField(max_length=10, null=True)),
                ('phos', models.CharField(max_length=10, null=True)),
                ('pot', models.CharField(max_length=10, null=True)),
                ('soil', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
