# Generated by Django 2.2.4 on 2020-02-01 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SIH', '0015_soil_detail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pest',
            name='Preventing',
        ),
        migrations.RemoveField(
            model_name='pest',
            name='Tips',
        ),
        migrations.RemoveField(
            model_name='pest',
            name='demage',
        ),
        migrations.RemoveField(
            model_name='pest',
            name='long_disc',
        ),
        migrations.AddField(
            model_name='pestsolution',
            name='Preventing',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pestsolution',
            name='Tips',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pestsolution',
            name='demage',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pestsolution',
            name='long_disc',
            field=models.TextField(null=True),
        ),
    ]
